title: Ziyan Ai's Homepage
page-top-title: Ai, Ziyan (Emma)
top-section-bg-text: Be what you wanna be
home-subtitle: Ai, Ziyan (Emma)
copyright-text: '&copy; Ziyan Ai 2025-2026. All Rights Reserved.'
